VERSION="2.2.1"

ACCOUNTS=[
"GDCLM6CEVNP6W4B3XFVDAJG6WBSUFWJQME2XOS6ROWBI7CQYCETJHGYU",
]

[DOCUMENTATION]
ORG_NAME="SkyTeam"
ORG_URL="https://www.skyteam-stellar.com/"
ORG_DESCRIPTION="Fly with us. Anywhere. Now with Stellar Network"
ORG_LOGO="https://www.skyteam-stellar.com/sta.png"


[[CURRENCIES]]
code="STA"
status="live"
display_decimals=2
issuer="GDCLM6CEVNP6W4B3XFVDAJG6WBSUFWJQME2XOS6ROWBI7CQYCETJHGYU"
anchor_asset_type="crypto"
name="SkyTeam"
desc="SkyTeam first and only Asset on Stellar Blockchain."
image="https://www.skyteam-stellar.com/sta.png"
fixed_number=1000000
max_number=1000000
is_unlimited=false
#SkyTeam Asset was issued using the open and inclusive Stellar blockchain network.
