VERSION="2.2.1"

ACCOUNTS=[
"GDCLM6CEVNP6W4B3XFVDAJG6WBSUFWJQME2XOS6ROWBI7CQYCETJHGYU",
"GA7FWTR22AIJYTJKP2LEUATRV22YVAFN3AH6LGXYJUF4FOMFICN5MNJ5",
"GDYNHSMEEKMBEGDJ5P2UPYLQTQ5GWWEAFWB5IHICFGSJK666S3PV4A2C",
"GBABLQXL6KVPRD3QKHWYOASO3HS2D5S52XL77XC2OOUHREE2ERJQ7YMF",
"GC3OL7OQULRKTIL2PTNOND6OFEPPATRNIA5RFHHRKXY2TSKAMHZHLVES",
]

[DOCUMENTATION]
ORG_NAME="SkyTeam"
ORG_URL="https://www.skyteam-stellar.com/"
ORG_DESCRIPTION="Fly with us. Anywhere. Now with Stellar Network"
ORG_LOGO="https://www.skyteam-stellar.com/sta.jpeg"


[[CURRENCIES]]
code="STA"
status="live"
display_decimals=2
issuer="GDCLM6CEVNP6W4B3XFVDAJG6WBSUFWJQME2XOS6ROWBI7CQYCETJHGYU"
anchor_asset_type="crypto"
name="SkyTeam"
desc="SkyTeam first and only Asset on Stellar Blockchain."
image="https://www.skyteam-stellar.com/sta.jpeg"
fixed_number=1000000
max_number=1000000

[[CURRENCIES]]
code="DAL"
status="live"
display_decimals=2
issuer="GA7FWTR22AIJYTJKP2LEUATRV22YVAFN3AH6LGXYJUF4FOMFICN5MNJ5"
anchor_asset_type="crypto"
name="Delta Air Lines"
desc="Delta Air Lines, a leader in domestic and international travel, offers airline tickets & flights to over 230 destinations in over 54 countries. Headquartered in Atlanta, Delta also has hubs in New York, Los Angeles, Boston, Seattle, Detroit, Minneapolis, and Salt Lake City."
image="https://www.skyteam-stellar.com/dal.jpg"
fixed_number=10000000
max_number=10000000

[[CURRENCIES]]
code="SAL"
status="live"
display_decimals=2
issuer="GDYNHSMEEKMBEGDJ5P2UPYLQTQ5GWWEAFWB5IHICFGSJK666S3PV4A2C"
anchor_asset_type="crypto"
name="Saudia"
desc="Saudia, formerly known as Saudi Arabian Airlines, is the flag carrier of Saudi Arabia, based in Jeddah. The airline's main hub is at King Abdulaziz International Airport in Jeddah and King Khalid International Airport in Riyadh."
image="https://www.skyteam-stellar.com/SAL.png"
fixed_number=10000000
max_number=10000000

[[CURRENCIES]]
code="GIA"
status="live"
display_decimals=2
issuer="GBABLQXL6KVPRD3QKHWYOASO3HS2D5S52XL77XC2OOUHREE2ERJQ7YMF"
anchor_asset_type="crypto"
name="Garuda Indonesia"
desc="Garuda Indonesia, the flagship airline of Indonesia, seamlessly connects more than 60 destinations worldwide."
image="https://www.skyteam-stellar.com/gia.jpg"
fixed_number=100000000
max_number=100000000

[[CURRENCIES]]
code="STLite"
status="live"
display_decimals=2
issuer="GC3OL7OQULRKTIL2PTNOND6OFEPPATRNIA5RFHHRKXY2TSKAMHZHLVES"
anchor_asset_type="crypto"
name="SkyTeam Lite"
desc="SkyTeam Lite will get everyone on board of the greatest Airline Alliances."
image="https://www.skyteam-stellar.com/stl.jpg"
fixed_number=1000000
max_number=1000000
